services:
  mongo:
    image: mongo
    env_file:
      - env/mongo.env
    environment:
      - MONGO_INITDB_DATABASE=${GATEWAY_MAIN_DATABASE:?}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:?}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:?}
      - MONGODB_URI=${MONGODB_URI:?}
    restart: always
    volumes:
      - ${MONGODB_DATA_VOLUME:?}:/data/db
    networks:
      - backend
