services:
  rabbitmq:
    image: rabbitmq:alpine
    env_file:
      - env/rabbitmq.env
    restart: always
    networks:
      - backend
    volumes:
      - ${RABBITMQ_CONFIG:?}:/etc/rabbitmq/conf.d
