version: '3'
networks:
  backend:
    external:
      name: backend

services:

  batch:
    image: coopengo/coog-bfm:${IMAGE_VERSION_COOG}
    container_name: batch-${BATCH_NAME}
    command: 
      - batch
      - "--"
      - ${BATCH_NAME}
      - ${BATCH_ARGS}
    env_file:
      - env_files/var.env
      - env_files/celery.env
    volumes:
      - ${COOG_VOLUME}:/workspace/io
      - ./conf/coog.conf:/workspace/coog.conf:ro
      - ./conf/batch.conf:/workspace/batch.conf:ro
    networks:
      - backend
  celery:
    image: coopengo/coog-bfm:${IMAGE_VERSION_COOG}
    command: 
      - celery 
      - ${NUM_WORKERS}
    container_name: celery-${BATCH_NAME}
    env_file:
      - env_files/var.env
      - env_files/celery.env
    volumes:
      - ${COOG_VOLUME}:/workspace/io
      - ./conf/coog.conf:/workspace/coog.conf:ro
      - ./conf/batch.conf:/workspace/batch.conf:ro
    networks:
      - backend
  redis:
    image: coopengo/coog-bfm:${IMAGE_VERSION_COOG}
    container_name: redis-${BATCH_NAME}
    command: 
      - redis
      - "--"
      - celery
      - qremove
      - ${BATCH_NAME}
    env_file:
      - env_files/var.env
      - env_files/celery.env
    volumes:
      - ${COOG_VOLUME}:/workspace/io
      - ./conf/coog.conf:/workspace/coog.conf:ro
      - ./conf/batch.conf:/workspace/batch.conf:ro
    networks:
      - backend
