[global]
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
      [docker.tls]
        cert = "/etc/certs/cert.pem"
        key = "/etc/certs/key.pem"
  [providers.file]
    filename = "/etc/traefik/traefik.config.toml"
    watch = true

[api]
  dashboard = true
  debug = false
  insecure = true

[certificatesResolvers.letsencrypt.acme]
  email = "support@coopengo.com"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  keyType = "EC256"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "http"
