services:
  b2c-front-common:
    image: ${IMAGE_REGISTRY:?}/${IMAGE_NAME_B2C_FRONT:?}:${IMAGE_VERSION_B2C_FRONT:?}
    user: 1000:1000
    env_file:
      # For some reason, we need to specify a relative path here
      # Might bug, I need to set the full path... (ex: /home/xxx/coog/coog-docker/env/b2c-front.env)
      - ../env/b2c-front.env
    environment:
      - B2C_FRONT_PATH_PREFIX=${B2C_FRONT_PATH_PREFIX:?}
      - API_URL=${B2C_FRONTEND_BUILD_INTERNAL_API_URL:?}
      - GATSBY_ROOT_URL=${BASE_URL}
      - GATSBY_API_URL=${B2C_BACKEND_EXTERNAL_URL:?}
    volumes:
      - ${B2C_FRONTEND_BUILD_VOLUME:?}:/workdir/public
