version: "3.9"

services:
  flower:
    image: mher/flower:0.9.5
    command: [" --url_prefix=flower"]
    user: "1003:1003"
    depends_on:
      - reverse-proxy
      - celery
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URI:?}
      - FLOWER_URL_PREFIX=flower
    labels:
      - traefik.enable=true
      - traefik.http.routers.flower.rule=Host(`${PROJECT_HOSTNAME:?}`) && PathPrefix(`/flower`)
      - traefik.http.routers.flower.entrypoints=http
      - traefik.http.routers.flower_s.rule=Host(`${PROJECT_HOSTNAME:?}`) && PathPrefix(`/flower`)
      - traefik.http.routers.flower_s.entrypoints=https
      - traefik.http.routers.flower_s.tls=true
    networks:
      - backend
      - frontend
    restart: always
