services:
  web:
    image: ${IMAGE_REGISTRY:?}/${IMAGE_NAME_WEB:?}:${IMAGE_VERSION_WEB:?}
    env_file:
      - env/web.env
    environment:
      - COOG_API_COOG_URL=${COOG_INTERNAL_URL:?}
      - COOG_API_COOG_DB=${COOG_MAIN_DATABASE:?}

      - COOG_API_MONGO_HOST=${MONGO_HOST:?}
      - COOG_API_MONGO_PORT=${MONGO_PORT:?}
      - COOG_API_MONGO_USER=${MONGO_USER:?}
      - COOG_API_MONGO_PASSWORD=${MONGO_PASSWORD:?}
      - COOG_API_MONGO_DB=${API_V1_MAIN_DATABASE:?}
      - COOG_API_MONGODB_URI=${MONGODB_URI:?}

      - COOG_API_API_PATH=/${API_V1_SUB_ROUTE:?}

      - DEBUG=${API_DEBUG_LEVEL:?}

      - OPENTELEMETRY_ENABLED=${OPEN_TELEMETRY_TRACING_ENABLED:?}
      - OPENTELEMETRY_URL=${OPEN_TELEMETRY_TRACING_URL:?}
      - OPENTELEMETRY_TOKEN=${OPEN_TELEMETRY_TRACING_TOKEN:?}
      - OPENTELEMETRY_SERVICE_NAME=${OPEN_TELEMETRY_SERVICE_NAME_WEB:?}
    command: ["server", "1"]
    depends_on:
      - mongo
    restart: always
    networks:
      - backend
