services:
  api:
    image: ${IMAGE_REGISTRY:?}/${IMAGE_NAME_API:?}:${IMAGE_VERSION_API:?}
    environment:
      - COOG_URL=${COOG_INTERNAL_URL:?}
      - COOG_DB_NAME=${COOG_MAIN_DATABASE:?}
      - JWT_INTERNAL_ENCRYPTION=${JWT_INTERNAL_ENCRYPTION:?}

      - COOG_API_V1_URL=${API_API_V1_INTERNAL_URL:?}
      - LOG_LEVEL=${COOG_LOG_LEVEL:?}

      - MONGO_HOST=${MONGO_HOST:?}
      - MONGO_PORT=${MONGO_PORT:?}
      - MONGO_DB_NAME=${API_V2_MAIN_DATABASE:?}
      - MONGO_USER=${MONGO_USER:?}
      - MONGO_PASSWORD=${MONGO_PASSWORD:?}
    depends_on:
      - mongo
    restart: always
    networks:
      - backend
