version: "3.9"

services:
  gateway:
    image: ${IMAGE_REGISTRY:?}/${IMAGE_NAME_GATEWAY:?}:${IMAGE_VERSION_GATEWAY:?}
    depends_on:
      - mongo
    env_file:
      - env/gateway.yml
    environment:
      - COOG_API_B2B_CONFIG_URL=${API_B2B_CONFIG_INTERNAL_URL:?}
      - COOG_API_B2C_URL=${API_B2C_INTERNAL_URL:?}
      - COOG_API_IDENTITY_MANAGER_URL=${API_IDENTITY_MANAGER_INTERNAL_URL:?}
      - COOG_API_REFERENTIAL_URL=${API_REFERENTIAL_INTERNAL_URL:?}
      - COOG_API_URL=${API_API_V1_INTERNAL_URL:?}
      - COOG_API_URL_V2=${API_API_V2_INTERNAL_URL:?}
      - COOG_API_V1_URL=${API_API_V1_INTERNAL_URL:?}
      - COOG_URL=${COOG_INTERNAL_URL:?}

      - COOG_GATEWAY_URL=${GATEWAY_EXTERNAL_URL:?}
      - COOG_PORTAL_URL=${PORTAL_EXTERNAL_URL:?}

      - COOG_GATEWAY_BASE_PATH="/${GATEWAY_SUB_ROUTE:?}"
      - COOG_GATEWAY_PORT=${COOG_GATEWAY_PORT:-3000}

      - WHITELIST=${CORS_WHITELIST:?}
      - COOG_WEB_TOKEN=${COOG_GATEWAY_TOKEN:?}

      - GOOGLE_MODULE=${ENABLE_GOOGLE_AUTHENTICATION:?}
      - COOG_MODULE=${ENABLE_COOG_AUTHENTICATION:?}
      - COOG_TOKEN_MODULE=${ENABLE_COOG_TOKEN_AUTHENTICATION:?}

      - JWT_ENCRYPTION=${JWT_ENCRYPTION:?}
      - JWT_EXPIRATION=${JWT_EXPIRATION:?}
      - JWT_INTERNAL_ENCRYPTION=${JWT_INTERNAL_ENCRYPTION:?}

      - MONGO_HOST=${MONGO_HOST:?}
      - MONGO_PORT=${MONGO_PORT:?}
      - MONGO_USER=${MONGO_USER:?}
      - MONGO_PASSWORD=${MONGO_PASSWORD:?}
    labels:
      - traefik.enable=true
      - traefik.http.routers.gateway.rule=Host(`${PROJECT_HOSTNAME:?}`) && PathPrefix(`/gateway`)
      - traefik.http.routers.gateway.entrypoints=http
      - traefik.http.routers.gateway.middlewares=gateway
      - traefik.http.middlewares.gateway.replacepathregex.regex=/gateway(/|$$)(.*)
      - traefik.http.middlewares.gateway.replacepathregex.replacement=/$${2:?}
      - traefik.http.routers.gateway_s.rule=Host(`${PROJECT_HOSTNAME:?}`) && PathPrefix(`/gateway`)
      - traefik.http.routers.gateway_s.middlewares=gateway_s
      - traefik.http.middlewares.gateway_s.replacepathregex.regex=/gateway(/|$$)(.*)
      - traefik.http.middlewares.gateway_s.replacepathregex.replacement=/$${2:?}
      - traefik.http.routers.gateway_s.entrypoints=https
      - traefik.http.routers.gateway_s.tls=true
    restart: always
    networks:
      - backend
      - frontend
