services:
  api-identity-manager:
    image: ${IMAGE_REGISTRY:?}/${IMAGE_NAME_API_IDENTITY_MANAGER:?}:${IMAGE_VERSION_API_IDENTITY_MANAGER:?}
    env_file:
      - env/api-identity-manager.env
    environment:
      - COOG_URL=${COOG_INTERNAL_URL:?}
      - COOG_DB_NAME=${COOG_MAIN_DATABASE:?}
      - JWT_INTERNAL_ENCRYPTION=${JWT_INTERNAL_ENCRYPTION:?}
      - MONGO_HOST=${MONGO_HOST:?}
      - MONGO_PORT=${MONGO_PORT:?}
      - MONGO_DB_NAME=${IDENTITY_MANAGER_MAIN_DATABASE:?}
      - MONGO_USER=${MONGO_USER:?}
      - MONGO_PASSWORD=${MONGO_PASSWORD:?}
      - MONGODB_URI=${MONGODB_URI:?}

      - OPENTELEMETRY_ENABLED=${OPEN_TELEMETRY_TRACING_ENABLED:?}
      - OPENTELEMETRY_URL=${OPEN_TELEMETRY_TRACING_URL:-}
      - OPENTELEMETRY_TOKEN=${OPEN_TELEMETRY_TRACING_TOKEN:-}
      - OPENTELEMETRY_SERVICE_NAME=${OPEN_TELEMETRY_SERVICE_NAME_IDENTITY_MANAGER:?}
    depends_on:
      - mongo
      - api
    restart: always
    networks:
      - backend
